on: 
  push:
    branches:
      - main 
  schedule:
    - cron: 7 0 * * 1-5
  workflow_dispatch:

jobs:
  check-for-updates:
    runs-on: ubuntu-latest
    outputs:
      update: ${{steps.update_step.outputs.update}}

    steps:
    - uses: actions/checkout@v3

    - id: update_step
      shell: pwsh
      name: Check for updates
      run: | 
        $updateResult = (.\updater.ps1 -orgName ${{ github.repository_owner }} -userName "xxx" -PAT ${{ secrets.GITHUB_TOKEN }} -issuesRepository ${{ github.repository }} )
        
        if ($null -ne $updateResult) {
          $reposWithUpdates = $updateResult[-1]
          Write-Host "Are there any updates available? [$($reposWithUpdates.Count -gt 0)]"
          echo "::set-output name=update::$($reposWithUpdates.Count -gt 0)"
        }