on: 
  issues:
    types: [labeled]

jobs:
  update-fork:
    runs-on: ubuntu-latest
    if: github.event.label.name == 'update-fork'

    steps:
    - uses: peter-murray/workflow-application-token-action@6a9741bf210c9a93370560585c908161170ecada # v2.1.0
      if: ${{ vars.use_github_app == 'true' }}
      id: get-workflow-token
      with:
        application_id: ${{ secrets.GH_AUTOMATION_ID }}
        application_private_key: ${{ secrets.GH_AUTOMATION_PRIVATE_KEY }}

    - id: get-token
      env: 
        github_app_token: ${{ steps.get-workflow-token.outputs.token }}
        PAT_GITHUB: ${{ secrets.PAT_GITHUB }}
      run: |
        if [ -z $github_app_token ]; then
          echo "token=$github_app_token" >> $GITHUB_OUTPUT
        else
          echo "token=$PAT_GITHUB" >> $GITHUB_OUTPUT
        fi

    - uses: actions/checkout@v2

    - run: |
       echo "Found the issue that triggered this event with number [${{ github.event.issue.number }}]"
       echo "Found the issue title [${{ github.event.issue.title }}]"

    - run: |
       .\update-fork.ps1 -orgName ${{ github.repository_owner }} -userName "xxx" -PAT ${{ steps.get-token.outputs.token }} -issueTitle "${{ github.event.issue.title }}" -issueId ${{ github.event.issue.number }} -issuesRepository  ${{ github.repository }}
      shell: pwsh