on: 
  push:
    branches:
      - main  

jobs:
  check-for-updates:
    runs-on: ubuntu-latest
    outputs:
      update: ${{steps.check-for-updates.update_step.updatesAvailable}}

    steps:
    - uses: actions/checkout@v1

    # call the script and store the result
    - run: updatesAvailable=$((pwsh -Command "& { .\updater.ps1 }") | tail -1) 
    
    - id: update_step
      run: echo "::set-output name=updatesAvailable::$updatesAvailable"

  run-update:
    runs-on: ubuntu-latest
    needs: check-for-updates
    steps:
    - run: echo 'hello world'
    #- run: echo "${{ jobs.check-for-updates.steps.update_step.outputs.updatesAvailable }}"
